### ISSUE TITLE
include simcc logo as new partner logo

### ISSUE THREAD

**Issue by cpsggisc** [buildingblocs/2021#18]
pls help add https://form.simcc.org/wp-content/uploads/2020/08/cropped-WhatsApp-Image-2020-01-11-at-13.28.52-1.jpeg to home page under partners thks!

**Comment by joelleoqiyi** [comment]
and also on the partner page, pls look thru SIMCC and give a suitable description

**Comment by ItsMeKimi** [comment]
Added to branch "going-online". Will be merged with main branch when other changes are made.

**Comment by ThinkerPal** [comment]
commit merged, will close the issue
